### ISSUE TITLE
Tray OnClick Override

### ISSUE THREAD

**Issue by jimbuck** [felixhao28/systray-portable#3]
Hey there! I was wondering how difficult it would be to override the tray click logic. By default, left click/right click both just show the menu. But would it be possible to "prevent default" and add custom logic? my end goal is use a custom handler for left click, but show the menu on right click. Thanks!

**Comment by felixhao28** [comment]
This will require the upstream project [systray](https://github.com/getlantern/systray) to capture which mouse key was used and then pass it down. For example on MacOS, related logic needs to be implemented here:

https://github.com/getlantern/systray/blob/2c0986dda9aea361e925f90e848d9036be7b5367/systray_darwin.m#L109:L113

This systray-portable project depends on this upstream project systray, which is not maintained by me. You can try opening an issue there for the feature request. However, systary hasn't seen any commits since last year.

**Comment by felixhao28** [comment]
Sorry I thought you were talking about the menu items. As for the menu itself, I actually don't know if we can control the showing-up behavior. It should be somewhere in the [systray](https://github.com/getlantern/systray) project too.

**Comment by felixhao28** [comment]
I think [this](https://github.com/getlantern/systray/issues/33) is what you are looking for.

**Comment by jimbuck** [comment]
Great, thank you!
